# require a super user permission
sudo: required
services:
  - docker

before_install:
  - docker build -t nwachuku/docker-react -f Dockerfile.dev .

#  The test script should be configured to run only once
script:
  - docker run -e CI=true nwachuku/docker-react npm run test