# require a super user permission
sudo: required
services:
  - docker

before_install:
  - docker build -t nwachuku/react-app -f Dockerfile.dev .

#  The test script should be configured to run only once
script:
  - docker run -e CI=true nwachuku/react-app npm run test

# bucket_path is usually the same name as your app
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-741032980292"
  bucket_path: "docker-react" 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"